name: CI/CD Pipeline

permissions:
  contents: read
  id-token: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      bun-version:           # ⬅︎ replace node-version with bun-version
        required: false      #   bun can default to “latest” if you don’t pass it
        type: string
        default: "latest"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun test
